# Generated by Django 6.0.6 on 2026-06-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KasKeluar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('jam', models.TimeField()),
                ('keterangan', models.TextField()),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=15)),
                ('users', models.CharField(max_length=100)),
            ],
        ),
    ]
