# Generated by Django 6.0.6 on 2026-06-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keuangan', '0002_kaskeluar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=100)),
                ('tgl_bergabung', models.DateField()),
            ],
        ),
    ]
